INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1430',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-12-24 14:16:26',
    'No',
    410.00,
    NULL,
    '2025-12-24 14:16:26',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1429',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-12-24 10:58:07',
    'No',
    410.00,
    NULL,
    '2025-12-24 10:58:07',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1428',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-12-20 15:30:26',
    'No',
    975.00,
    NULL,
    '2025-12-20 15:30:26',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    5
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1427',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-12-19 15:46:25',
    'No',
    410.00,
    NULL,
    '2025-12-19 15:46:25',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1426',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-12-09 11:05:53',
    'No',
    205.00,
    NULL,
    '2025-12-09 11:05:53',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1425',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-12-08 11:07:48',
    'No',
    410.00,
    NULL,
    '2025-12-08 11:07:48',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1424',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-12-03 14:25:11',
    'No',
    209.10,
    NULL,
    '2025-12-03 14:25:11',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1423',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-11-26 15:39:44',
    'No',
    410.00,
    NULL,
    '2025-11-26 15:39:44',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1422',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-11-18 18:05:00',
    'No',
    410.00,
    NULL,
    '2025-11-18 18:05:00',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1421',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-11-16 07:29:42',
    'No',
    210.00,
    NULL,
    '2025-11-16 07:29:42',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1420',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-11-14 12:06:25',
    'No',
    410.00,
    NULL,
    '2025-11-14 12:06:25',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1419',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-11-09 18:39:56',
    'No',
    410.00,
    NULL,
    '2025-11-09 18:39:56',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1418',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-11-05 13:46:38',
    'No',
    415.00,
    NULL,
    '2025-11-05 13:46:38',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1417',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-11-04 16:56:55',
    'No',
    415.00,
    NULL,
    '2025-11-04 16:56:55',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1416',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-10-31 18:38:37',
    'No',
    210.00,
    NULL,
    '2025-10-31 18:38:37',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1415',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-10-28 17:25:18',
    'No',
    410.00,
    NULL,
    '2025-10-28 17:25:18',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1414',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-10-26 19:00:05',
    'No',
    410.00,
    NULL,
    '2025-10-26 19:00:05',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1413',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-10-24 09:25:56',
    'No',
    205.00,
    NULL,
    '2025-10-24 09:25:56',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1412',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-10-24 08:18:04',
    'No',
    205.00,
    NULL,
    '2025-10-24 08:18:04',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1411',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-10-14 11:52:39',
    'No',
    210.00,
    NULL,
    '2025-10-14 11:52:39',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1410',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-10-13 22:43:30',
    'No',
    410.00,
    NULL,
    '2025-10-13 22:43:30',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1409',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-10-13 13:22:05',
    'No',
    410.00,
    NULL,
    '2025-10-13 13:22:05',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1408',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-10-12 13:30:32',
    'No',
    410.00,
    NULL,
    '2025-10-12 13:30:32',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1407',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-10-08 10:43:29',
    'No',
    410.00,
    NULL,
    '2025-10-08 10:43:29',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1406',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-10-05 13:49:02',
    'No',
    410.00,
    NULL,
    '2025-10-05 13:49:02',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1405',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-10-01 15:43:43',
    'No',
    210.00,
    NULL,
    '2025-10-01 15:43:43',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1404',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-09-26 10:07:27',
    'No',
    205.00,
    NULL,
    '2025-09-26 10:07:27',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1403',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-09-23 18:40:42',
    'No',
    410.00,
    NULL,
    '2025-09-23 18:40:42',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1401',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-09-20 12:08:24',
    'No',
    410.00,
    NULL,
    '2025-09-20 12:08:24',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1400',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-09-13 11:50:33',
    'No',
    410.00,
    NULL,
    '2025-09-13 11:50:33',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1399',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-09-10 21:59:03',
    'No',
    410.00,
    NULL,
    '2025-09-10 21:59:03',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1398',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-08-30 16:26:40',
    'No',
    415.00,
    NULL,
    '2025-08-30 16:26:40',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1397',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-08-27 15:47:35',
    'No',
    37.99,
    NULL,
    '2025-08-27 15:47:35',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1396',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-08-23 10:58:08',
    'No',
    210.00,
    NULL,
    '2025-08-23 10:58:08',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1395',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-08-18 20:54:51',
    'No',
    410.00,
    NULL,
    '2025-08-18 20:54:51',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1394',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-08-06 10:39:22',
    'No',
    205.00,
    NULL,
    '2025-08-06 10:39:22',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1393',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-08-03 13:42:04',
    'No',
    410.00,
    NULL,
    '2025-08-03 13:42:04',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1392',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-07-30 15:14:49',
    'No',
    205.00,
    NULL,
    '2025-07-30 15:14:49',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1391',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-07-10 23:57:50',
    'No',
    209.10,
    NULL,
    '2025-07-10 23:57:50',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1387',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-07-07 15:14:44',
    'No',
    205.00,
    NULL,
    '2025-07-07 15:14:44',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1385',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-06-29 19:13:48',
    'No',
    205.00,
    NULL,
    '2025-06-29 19:13:48',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1384',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-06-19 12:59:59',
    'No',
    410.00,
    NULL,
    '2025-06-19 12:59:59',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1383',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-06-18 10:38:36',
    'No',
    205.00,
    NULL,
    '2025-06-18 10:38:36',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1382',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-06-18 09:34:12',
    'No',
    410.00,
    NULL,
    '2025-06-18 09:34:12',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1381',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-06-16 17:08:20',
    'No',
    205.00,
    NULL,
    '2025-06-16 17:08:20',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1380',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-06-12 19:47:21',
    'No',
    205.00,
    NULL,
    '2025-06-12 19:47:21',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1378',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-06-09 13:54:06',
    'No',
    410.00,
    NULL,
    '2025-06-09 13:54:06',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1375',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-04-25 09:58:26',
    'No',
    410.00,
    NULL,
    '2025-04-25 09:58:26',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1373',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-03-28 21:31:53',
    'No',
    205.00,
    NULL,
    '2025-03-28 21:31:53',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1370',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-03-22 08:58:07',
    'No',
    415.00,
    NULL,
    '2025-03-22 08:58:07',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1366',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-02-08 14:52:32',
    'No',
    415.00,
    NULL,
    '2025-02-08 14:52:32',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1363',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-01-29 17:58:49',
    'No',
    210.00,
    NULL,
    '2025-01-29 17:58:49',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1362',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-01-17 10:20:40',
    'No',
    205.00,
    NULL,
    '2025-01-17 10:20:40',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1361',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-01-08 22:34:32',
    'No',
    209.10,
    NULL,
    '2025-01-08 22:34:32',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1360',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-01-08 11:48:09',
    'No',
    410.00,
    NULL,
    '2025-01-08 11:48:09',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1355',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2026-12-24 09:03:25',
    'No',
    410.00,
    NULL,
    '2024-12-24 09:03:25',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1354',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2026-12-19 11:18:58',
    'No',
    205.00,
    NULL,
    '2024-12-19 11:18:58',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1353',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2026-12-18 18:47:05',
    'No',
    410.00,
    NULL,
    '2024-12-18 18:47:05',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1352',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2026-12-18 18:02:44',
    'No',
    410.00,
    NULL,
    '2024-12-18 18:02:44',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1350',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2026-12-15 20:41:18',
    'No',
    210.00,
    NULL,
    '2024-12-15 20:41:18',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1348',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2026-12-12 08:38:37',
    'No',
    410.00,
    NULL,
    '2024-12-12 08:38:37',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1345',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2026-12-02 09:28:23',
    'No',
    205.00,
    NULL,
    '2024-12-02 09:28:23',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1343',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2026-11-30 16:59:59',
    'No',
    369.00,
    NULL,
    '2024-11-30 16:59:59',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1339',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2026-10-16 11:32:48',
    'No',
    210.00,
    NULL,
    '2024-10-16 11:32:48',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1335',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2026-08-27 21:07:46',
    'No',
    205.00,
    NULL,
    '2024-08-27 21:07:46',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1334',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2026-08-18 01:44:57',
    'No',
    205.00,
    NULL,
    '2024-08-18 01:44:57',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1332',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2026-07-26 09:40:38',
    'No',
    410.00,
    NULL,
    '2024-07-26 09:40:38',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1329',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2026-07-06 22:11:14',
    'No',
    410.00,
    NULL,
    '2024-07-06 22:11:14',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1327',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2026-06-22 13:03:33',
    'No',
    415.00,
    NULL,
    '2024-06-22 13:03:33',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1326',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2026-06-14 20:49:19',
    'No',
    405.00,
    NULL,
    '2024-06-14 20:49:19',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB1325',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2026-06-09 16:56:59',
    'No',
    205.00,
    NULL,
    '2024-06-09 16:56:59',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB9900',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2026-06-09 16:56:59',
    'No',
    410,
    NULL,
    '2024-06-09 16:56:59',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB24000',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2026-06-09 16:56:59',
    'No',
    205,
    NULL,
    '2024-06-09 16:56:59',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1
);

INSERT INTO trip_booking.all_vouchers (
    voucher_ref,
    name,
    purchaser_name,
    purchaser_email,
    purchaser_phone,
    purchaser_mobile,
    experience_type,
    book_flight,
    voucher_type,
    voucher_type_detail,
    email,
    expires,
    redeemed,
    paid,
    offer_code,
    created_at,
    status,
    voucher_code,
    weight,
    mobile,
    phone,
    recipient_name,
    recipient_email,
    recipient_phone,
    recipient_gift_date,
    preferred_location,
    preferred_time,
    preferred_day,
    flight_attempts,
    numberOfPassengers
) VALUES (
    'FAB139800',
    'Shopify',
    'Shopify',
    NULL,
    NULL,
    NULL,
    'Shared Flight',
    'Flight Voucher',
    'Any Day Flight',
    NULL,
    NULL,
    '2027-09-08 16:00:45',
    'No',
    370.00,
    NULL,
    '2025-09-08 16:00:45',
    'active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    2
);